name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  GO111MODULE: on

jobs:

  golangci-lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - uses: actions/checkout@v4.1.0

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose

  test-unix:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu
        go:
        - 21
    name: '${{ matrix.platform }} | 1.${{ matrix.go }}.x'
    runs-on: ${{ matrix.platform }}-latest
    steps:

    - uses: actions/setup-go@v4
      with:
        go-version: 1.${{ matrix.go }}.x

    - uses: actions/checkout@v4.1.0

    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-1.${{ matrix.go }}.x-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-1.${{ matrix.go }}.x-

    - run: PATH=$HOME/go/bin/:$PATH make test build
