name: Go test coverage check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

    go-test-coverage:
        runs-on: ubuntu-latest
        steps:

        - uses: actions/setup-go@v4
          with:
            go-version: '1.21'
        
        - uses: actions/checkout@v4.1.0

        - name: generate test coverage
          run: go test ./... -race -coverprofile=coverage.out -covermode=atomic

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
