name: Go test coverage check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

    go-test-coverage:
        runs-on: ubuntu-latest
        steps:

        - uses: actions/setup-go@v4
          with:
            go-version: '1.20'
        
        - uses: actions/checkout@v4.1.0

        - name: generate test coverage
          run: go test ./... -coverprofile=./cover.out

        - name: check test coverage
          uses: vladopajic/go-test-coverage@v2
          with:
            config: ./.testcoverage.yml
